version: '3'
services:
  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui
    ports:
      - 8080:8080
    command: ["--selenoid-uri", "http://selenoid:4444"]
    links:
      - ggr-ui
      - selenoid

  ggr-ui:
    network_mode: bridge
    restart: always
    image: aerokube/ggr-ui:latest-release
    ports:
      - 8888:8888
    volumes:
       - /Users/yantoniuk/Desktop/webTests/etc/grid-router:/etc/grid-router:ro

  ggr:
    network_mode: bridge
    image: aerokube/ggr:latest-release
    ports:
      - 4446:4446
    restart: always
    volumes:
      - /Users/yantoniuk/Desktop/webTests/etc/grid-router:/etc/grid-router:ro
    command: [ "-listen", ":4446"]

  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - "/Users/yantoniuk/Desktop/webTests/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/yantoniuk/Desktop/webTests/config:/opt/selenoid/video"
      - "/Users/yantoniuk/Desktop/webTests/config:/opt/selenoid/logs"
    ports:
      - 4445:4444
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/yantoniuk/Desktop/webTests/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/log"]
