version: '3'
services:
  ggr-ui:
    image: aerokube/ggr-ui:latest-release
    ports:
      - 8888:8888
    volumes:
      - /etc/grid-router:/etc/grid-router:ro

  ggr:
    image: aerokube/ggr:latest-release
    ports:
      - 5555:5555
    restart: unless-stopped
    volumes:
      - /etc/grid-router:/etc/grid-router:ro
    command: [ "-listen", ":5555" ]

  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444"]

  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - "/Users/yantoniuk/Desktop/webTests/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/yantoniuk/Desktop/webTests/config:/opt/selenoid/video"
      - "/Users/yantoniuk/Desktop/webTests/config:/opt/selenoid/logs"
    ports:
      - "4444:4444"

    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/yantoniuk/Desktop/webTests/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/log"]