version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "/Users/yantoniuk/Desktop/webTests/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/yantoniuk/Desktop/webTests/config/video:/opt/selenoid/video"
      - "/Users/yantoniuk/Desktop/webTests/config/logs:/opt/selenoid/logs"

    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/yantoniuk/Desktop/webTests/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]